### ISSUE TITLE
Service collection for Blazor-WebAssembly

### ISSUE THREAD

**Issue by jolaquai** [jolaquai/LaquaiLib#9]
- FileSystemProxy (r/w files, `.Exists` checks, basically just replicate the entire `File` and `Directory` types)
- ...

**Comment by KliqxTV** [comment]
# Wasm Services
`Wasm Services` is a series of services you can inject into a Blazor WebAssembly project when hosting it inside a Forms, WPF or MAUI application using the platform's respective `BlazorWebView` variant.

Because of the sandboxed nature of a wasm app, namely being contained in a web browser instance, things like host file system access are not directly possible, but types ("services") that are instantiated outside the wasm app and then injected into it as a service _are_ able to do so.

While this may introduce serious security flaws, when in a controlled environment, this is actually extremely useful and, of course, not limited to just file system access.

I intend to only include very broad-spectrum services here; prime example, again, `FileSystemProxy`, which, when injected, allows full access to the file system using static methods which proxy (parts of) `System.IO`.
